server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    view:
      prefix: /
      suffix: html
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:sqlite:path_to_your_database/database.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always