name: Build Java tgDrive (Maven) and Push ARM Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: tgDrive-java-jar
          path: target/*.jar

  docker-push-arm64:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: tgDrive-java-jar
          path: target/

      - name: Install QEMU for ARM64
        run: |
          sudo apt-get update
          sudo apt-get install qemu-user-static -y
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - name: Build ARM64 Docker image
        run: |
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME="yuzunyaa/tgdrivearm"
          IMAGE_TAG=latest
          PLATFORM="linux/arm64"

          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build --platform $PLATFORM -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Inspect ARM64 Docker Image Architecture
        run: docker image inspect yuzunyaa/tgdrivearm:latest --format='{{.Architecture}} {{.Os}}'
