name: Build ARM

on:
  push:
    branches: [ main ]

jobs:
  build-ARM:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install QEMU and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static qemu-utils
          sudo apt-get install -y build-essential

      - name: Setup QEMU binfmt
        run: |
          sudo docker run --rm --privileged multiarch/qemu-user-static:register

      - name: Build for ARM
        run: |
          export CC=/usr/bin/arm-linux-gnueabi-gcc
          export CXX=/usr/bin/arm-linux-gnueabi-g++
          ./configure --host=arm-linux-gnueabi
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ARM-binary
          path: ./path/to/binary
