name: Build ARM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu-user-static -y

      - name: Set up ARM build environment
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - name: Initialize Go Module
        run: go mod init github.com/SkyDependence/tgDrive

      - name: Debug directory structure
        run: |
          pwd
          ls -al

      - name: Build ARM binary
        run: |
          pwd
          ls -al

          cd src/main
          pwd
          ls -al

          GOOS=linux GOARCH=arm GOARM=7
          export GOROOT_BOOTSTRAP=$GOROOT
          mkdir -p build/arm
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o build/arm/tgDrive ./

      - name: Upload ARM binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: tgDrive-arm-binary
          path: build/arm/tgDrive
